BduProject/BduProject/Controllers/FilesController.cs
using BduProject.Repository;
using BduProject.Repository.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BduProject.Controllers
{
    [Authorize(Roles = "Tyutor,Lawyer")]
    [Route("files")]
    public class FilesController : Controller
    {
        private readonly IGetFile _getFile;
        public FilesController(IGetFile getFile)
        {
            _getFile = getFile;
        }
        public IActionResult Index(int id)
        {
            MyFile file = _getFile.Get(id);
            string contetnType = file.Path.Substring(file.Path.Length - 3);
            var stream = new FileStream(file.Path, FileMode.Open);
            if (contetnType == "pdf")
            {
                return new FileStreamResult(stream, "application/pdf");
            }
            if (contetnType == "peg")
            {
                return new FileStreamResult(stream, "image/jpeg");
            }
            if (contetnType == "jpg")
            {
                return new FileStreamResult(stream, "image/jpg");
            }
            throw new Exception();

        }
    }
}

BduProject/BduProject/Controllers/TyutorController.cs
using BduProject.Model;
using BduProject.Repository;
using BduProject.Repository.Interfaces;
using BduProject.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BduProject.Controllers
{
    [Route("tyutor")]
    [Authorize(Roles = "Tyutor")]
    public class TyutorController : Controller
    {
        private IGetAbituriyents _getAbituriyents;
        private IGetAbituriyent _getAbituriyent;
        private ISendMail _sendMail;
        private IGetCode _getCode;
        private IUpdateAbituriyent _updateAbituriyent;
        private  IGetFile _getFile;

        public TyutorController(IGetAbituriyents getAbituriyents,IUpdateAbituriyent updateAbituriyent,
            IGetAbituriyent getAbituriyent,ISendMail sendMail,IGetCode getCode,IGetFile getFile)
        {
            _updateAbituriyent = updateAbituriyent;
            _getAbituriyents = getAbituriyents;
            _getAbituriyent = getAbituriyent;
            _sendMail = sendMail;
            _getCode = getCode;
            _getFile = getFile;
        }
        public IActionResult Index()
        {
            return View(_getAbituriyents.GetAll());
        }
        [HttpGet]
        [Route("details")]
        public IActionResult Details(int id)
        {
            AbituriyentFile abituriyentFile = new AbituriyentFile();
            abituriyentFile.Abituriyent = _getAbituriyent.Get(id);
            abituriyentFile.Files = _getFile.GetAll(id);
            return View(abituriyentFile);
        }
        [HttpPost]
        [Route("finish")]
        public IActionResult Finish(int id)
        {
            _updateAbituriyent.UpdateStatus(id, "Completed");
            return RedirectToAction("Index", "Tyutor");

        }
        [HttpPost]
        [Route("reject")]
        public IActionResult Reject(int id)
        {
            _updateAbituriyent.UpdateStatus(id, "Rejected");
            return RedirectToAction("Index", "Tyutor");
        }
        [HttpPost]
        [Route("tolawyer")]
        public IActionResult ToLawyer(int id)
        {
            _updateAbituriyent.UpdateStatus(id, "InLawyer");
            return RedirectToAction("Index", "Tyutor");

        }
    }
}

BduProject/BduProject/Views/Tyutor/Details.cshtml
@model BduProject.Model.AbituriyentFile
@{
    Layout = "_Layout";
}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css2?family=Alata&display=swap" rel="stylesheet">
</head>
<body>
    <table class="table">
        <thead>
            <tr>
                <th>
                    <h5>Şəxsi Informasiya</h5>
                </th>
                <th>
                    <h5>Sənədlər</h5>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <dl class="dl-horizontal">

                        <dt>
                            @Html.DisplayNameFor(model => model.Abituriyent.Name)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Abituriyent.Name)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.Abituriyent.Surname)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Abituriyent.Surname)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.Abituriyent.Father)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Abituriyent.Father)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.Abituriyent.Email)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Abituriyent.Email)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.Abituriyent.FIN)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Abituriyent.FIN)
                        </dd>
                    </dl>
                </td>
                <td>
                    @foreach (var item in Model.Files)
                    {

                        <a  asp-action="Index" asp-controller="Files" asp-route-id="@item.Id" >@item.FileName</a>
                        <br />
                    }
                </td>
            </tr>
        </tbody>
    </table>
    <input type="hidden" asp-for="Abituriyent.Id" />
    @if (Model.Abituriyent.Status != "Completed" )
    {
        @if (Model.Abituriyent.Status == "LastStep" || Model.Abituriyent.TehsilNovu != "Imtiyazli")
        {
            <button type="submit" class="btn btn-success" asp-action="Finish" asp-controller="Tyutor" asp-route-id="@Model.Abituriyent.Id">Finish</button>
        }
        @if (Model.Abituriyent.Status != "LastStep" && Model.Abituriyent.TehsilNovu == "Imtiyazli" && Model.Abituriyent.Status != "InLawyer")
        {
            <button type="submit" class="btn btn-success" asp-action="ToLawyer" asp-controller="Tyutor" asp-route-id="@Model.Abituriyent.Id">Lawyere Yolla</button>
        }
        @if (Model.Abituriyent.Status == "InLawyer")
        {
            <p>Lawyer Gozlenilir...</p>
        }
        @if (Model.Abituriyent.Status != "InLawyer")
        {
            <button type="submit" class="btn btn-danger" asp-action="Reject" asp-controller="Tyutor" asp-route-id="@Model.Abituriyent.Id">Redd et</button>
        }
    }

    <style>
        html, body {
            height: 100%;
            background-color: #f5f5f5;
            font-family: 'Alata', sans-serif;
        }

        .form-container {
            border-radius: 20px;
            padding: 2% 2%;
            max-width: 70%;
            margin: 2% auto;
            background-color: white;
            justify-content: center;
            align-items: center;
        }
    </style>
</body>
</html>

BduProject/BduProject/Views/Tyutor/Index.cshtml
@model IEnumerable<BduProject.Model.Abituriyent>
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Table</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.17.1/dist/bootstrap-table.min.css">


    <script src="https://unpkg.com/bootstrap-table@1.17.1/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.17.1/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow">
        <div style="padding-right:2%">
            <img class="profile-img" src="~/images/bsu.jpeg" />
        </div>

        <h2>@User.FindFirst("FakulteName").Value</h2>
    </nav>
    <div class="container shadow">

        <table id="table"
               data-toggle="table"
               data-show-pagination-switch="true"
               data-search-align="left"
               data-filter-control="true"
               data-show-export="true"
               data-click-to-select="true"
               data-toolbar="#toolbar"
               data-pagination="true"
               data-height="100vh">
            <thead>
                <tr>

                    <th data-field="ad" data-filter-control="input" data-sortable="true">Ad</th>
                    <th data-field="soyad" data-filter-control="input" data-sortable="true">Soyad</th>
                    <th data-field="ataAdı" data-filter-control="input" data-sortable="true">Ata adı</th>
                    <th data-field="fin" data-filter-control="input" data-sortable="true">Fin</th>
                    <th data-field="status" data-filter-control="select" data-sortable="true">Status</th>
                    <th data-field="details">Info</th>

                </tr>
            </thead>


            <tbody>

                @foreach (var item in Model)
                {
                    @if(item.Fakulte != User.FindFirst("FakulteName").Value)
                    {
                        continue;
                    }
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.Surname</td>
                        <td>@item.Father</td>
                        <td>@item.FIN</td>
                        <td>
                            @if (item.Status == "" || item.Status == null || item.Status == "def")
                            {
                                <p>InProgress</p>
                            }
                            @if (@item.Status == "InLawyer")
                            {
                                <p style="color : red">InLawyer</p>
                            }
                            @if (@item.Status == "LastStep" && @item.TehsilNovu == "Imtiyazli")
                            {
                                <p style="color : yellow">LastStep</p>
                            }
                            @if (@item.Status == "Rejected")
                            {
                                <p style="color : red">Rejected</p>
                            }
                            @if (@item.Status == "Edit")
                            {
                                <p style="color : lime">Editting</p>
                            }
                            @if (@item.Status == "Completed")
                            {
                                <p style="color : green">Completed</p>
                            }
                            @if (@item.Status == "Accepted")
                            {
                                <p style="color : greenyellow">Accepted</p>
                            }
                        </td>
                        <td><a  asp-controller="Tyutor" asp-action="Details" asp-route-id="@item.Id"><button class="button btn-primary" style="color : white">Details</button></a></td>
                    </tr>
                }

            </tbody>
        </table>
    </div>

    <style>
        .container {
            width: 100vw;
            /* padding: 1vw 1vh; */
            background-color: white;
            margin: 2% auto;
            justify-content: center;
            align-items: center;
        }

        .profile-img {
            width: 15vh;
            height: 15vh;
            margin: 0 auto 10px;
            display: block;
            -moz-border-radius: 50%;
            -webkit-border-radius: 50%;
            border-radius: 50%;
        }

        body {
            font-family: 'Nunito', sans-serif;
            background-color: #e9e9e9;
        }

        a:link {
            text-decoration: none;
        }
    </style>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>



</body>
</html>